name: flutter_architecture
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  go_router: ^16.2.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  custom_lint: ^0.6.7 #analysisの問題を解決するために追加
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
