name: flutter_architecture
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  go_router: ^16.2.0
  shared_preferences: ^2.5.3
  dio: ^5.9.0
  openapi_generator_annotations: ^6.1.0

  logger: ^2.6.0

  # Generated API client
  miracle_api_client:
    path: lib/external/http/generate/api

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  custom_lint: ^0.6.7 #analysisの問題を解決するために追加
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

  flutter_gen_runner: ^5.10.0

  flutter_lints: ^5.0.0

  mockito: ^5.4.5

  openapi_generator: ^6.1.0

flutter_gen:
  output: lib/ui/style/gen/
  integrations:
    flutter_svg: true
  assets:
    outputs:
      class_name: Assets

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansJP-SemiBold.ttf
          weight: 600
